# My variables
name: Russell Smith
description: developer
google_analytics: UA-21697883-3
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
